### ISSUE TITLE
Quiz Feedback

### ISSUE THREAD

**Issue by aditiopangestu** [putueddy/nxt-level2-quiz#1]
Masya Allah, secara fungsional sudah aman mas, sedikit feedback dari source code nya, penggunaan key untuk rendering list kurang tepat menggunakan index, bisa dibaca di https://beta.reactjs.org/learn/rendering-lists#why-does-react-need-keys.

Berhubung waktu masih panjang, silahkan kerjakan bonus yang disediakan.

Hint:
- Bonus pertama dapat dikerjakan dengan membuat state untuk error message
- Bonus kedua dapat dikerjakan menggunakan useRef

**Comment by afiiif** [comment]
Mantab Mas @putueddy, barokallahufiik...

Saya ada sedikit tambahan feedback biar lebih baik lagi:

1️⃣  
Penamaan variable `quote` & `setQuote` menurut saya bisa lebih deskriptif lagi spt `formValues` & `setFormValues`

2️⃣  
Bisa manfaatkan destructuring variable,
```
MyComponent({ prop1, prop2, ... }) {
  // code
}

// atau

MyComponent(props) {
  const { prop1, prop2 } = props;
  // code
}
```
