### ISSUE TITLE
Quiz Feedback Part 2

### ISSUE THREAD

**Issue by aditiopangestu** [putueddy/nxt-level2-quiz#3]
Pesan error yang ditampilkan masih seragam, contoh saat user belum mengisi email seharusnya pesan error yang muncul "Email is required", saat user sudah mengisi email dan formatnya salah baru muncul pesan error "Email is invalid". Untuk menghandle ini bisa dilakukan dg menyimpan pesan error yang mau ditampilkan pada input, bukan meyimpan flag apakah input ini valid atau tidak. Silahkan di update mas.

Value yg diassign ke key masih salah juga mas.

**Comment by udiiin** [comment]
Halo mas @putueddy, maaf nih baru sempat re-check lagi..

Kalo utk issue soal error message yg dibilang Mas @aditiopangestu itu saya lihat udah solved ✅  
Saya rasa sudah bisa lanjut ke level berikutnya.

Paling feedback dikit nih dari saya, terkait state error message ini saya rasa masih kurang efisien.  
Sebenernya bisa gini aja:

```js
const [errors, setErrors] = useState({
  name: '',
  email: '', // 👈 Ini nanti diisi dg "Email is required", "Email is invalid", atau kosong utk menandakan bahwa inputnya sudah valid
  phone: '',
  company: '',
})
```

Tapi secara functional udah oke 👍  
Barokallaahu fiik

**Comment by putueddy** [comment]
Syukron feedbacknya mas @udiiin. Akan saya coba sederhanakan state inputValid menjadi state errors di atas.
Jazakallah khayr
